In [3]:
# ! pip install pandas

import pandas as pd
import numpy as np

print(pd.__version__)

2.0.1


In [5]:
## list

a = [1,2,3,4]

a[1:3]

##
b = [[1,2],[3,4,5]]
print(b)

##
c = [10, 'apple', True]

np.array(c)

[[1, 2], [3, 4, 5]]


array(['10', 'apple', 'True'], dtype='<U11')

In [11]:
## numpy

a = np.array([0,1,2,3,4])
print("a = ",a)
print(type(a))

print(a[2:])

## attribute
print("shape = ",a.shape)
print("dtype = ",a.dtype)

a =  [0 1 2 3 4]
<class 'numpy.ndarray'>
[2 3 4]
shape =  (5,)
dtype =  int32


In [13]:
print(list(range(1,5)))

array = np.array([range(i, i+2) for i in [1, 4, 7]])
print(array)

print(array.shape)
print(array.dtype)

[1, 2, 3, 4]
[[1 2]
 [4 5]
 [7 8]]
(3, 2)
int32


In [15]:
a = np.array([0, 1])
b = np.array([[0, 1]])

print(a.shape, a)
print(b.shape, b)

(2,) [0 1]
(1, 2) [[0 1]]


In [19]:
##
print(np.eye(3,5))
print()

print(np.identity(3))
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
##
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.full((5,4), 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [23]:
##
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [25]:
## range

print(list(range(1,8,2)))

print(np.arange(1,8,2))

[1, 3, 5, 7]
[1 3 5 7]


In [29]:
a = np.arange(1,10,2)
b = np.arange(3,12,2)

c = np.array([a,b],dtype=np.int64)


print(c)
print()
print("shape = ",c.shape)
print("dtype = ",c.dtype)

[[ 1  3  5  7  9]
 [ 3  5  7  9 11]]

shape =  (2, 5)
dtype =  int64


In [32]:
a = np.identity(5, dtype= np.int64) * 2

print(a)

print("shape = ", a.shape)
print("dtype = ", a.dtype)

[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 2]]
shape =  (5, 5)
dtype =  int64


In [36]:
array = np.arange(12)
arr_3by4 = array.reshape(3,4)
arr_4by3 = array.reshape(4,3)
arr_5by3 = array.reshape(-1,3)
arr_5by2 = array.reshape(-1,2)

print(array)
print()
print(arr_3by4)
print()
print(arr_4by3)
print()
print(arr_5by3)
print()
print(arr_5by2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [38]:
print(arr_5by3)
print(list(arr_5by3.flat))
print(arr_5by3.T)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [43]:
a = np.array([[[0],[1],[2]]])

print(a)
print(a.shape)
print()
print(a.reshape(1,1,3))
print()
print(a.reshape(3,1,1))

[[[0]
  [1]
  [2]]]
(1, 3, 1)

[[[0 1 2]]]
[[[0]]

 [[1]]

 [[2]]]


In [47]:
print(a)
print(a.shape)

a.squeeze()
print(a.squeeze(axis= 0))
print(a.squeeze(axis= 0).shape)
print()
print(a.squeeze(axis= 2))
print(a.squeeze(axis= 2).shape)

[[[0]
  [1]
  [2]]]
(1, 3, 1)
[[0]
 [1]
 [2]]
(3, 1)

[[0 1 2]]
(1, 3)


In [49]:
## vstack

a = np.array([1,2,3])
b = np.array([3,5,1])
c = np.array([1,4,4])

d =np.vstack([a,b,c])
print(d)

[[1 2 3]
 [3 5 1]
 [1 4 4]]


In [53]:
#a = np.array([1,2,3])
#b = np.array([3,5,1])

a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])

print("hstack = \n", np.hstack([a,b]))
print("vstack = \n", np.vstack([a,b]))

hstack = 
 [[1 4]
 [2 5]
 [3 6]]
vstack = 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [57]:
a = np.arange(1,6)
b = np.arange(2,7)

print(a,b)
print("hstack = \n", np.hstack([a,b]))
print("vstack = \n", np.vstack([a,b]))
print("column_stack = \n", np.column_stack([a,b]))


[1 2 3 4 5] [2 3 4 5 6]
hstack = 
 [1 2 3 4 5 2 3 4 5 6]
vstack = 
 [[1 2 3 4 5]
 [2 3 4 5 6]]
column_stack = 
 [[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]


In [61]:
A = [[1,2,3,4],
     [2,4,5,8]]

B = [6,6,5,4]

AB = np.vstack([A,B])
print(AB)
print(AB.T)

[[1 2 3 4]
 [2 4 5 8]
 [6 6 5 4]]
[[1 2 6]
 [2 4 6]
 [3 5 5]
 [4 8 4]]


In [63]:
## random sampling

## Uniform(균일분포), integer uniform, gaussian 분포(정규분포)

print(np.random.rand(5))
print(np.random.rand(3,5))

[0.01246926 0.97831345 0.13538125 0.64464314 0.10793951]
[[0.26690577 0.75989944 0.16134784 0.46790766 0.56979753]
 [0.45750847 0.00951737 0.47068692 0.01344995 0.41384831]
 [0.50784726 0.23180919 0.82086258 0.19930984 0.85203581]]


In [65]:
np.random.randint(1,10,(3,2))

array([[6, 4],
       [3, 2],
       [2, 9]])

In [81]:
#np.random.seed(503)
#np.random.randn(100)
np.random.normal(172,1,(3,3))

array([[171.96989384, 171.60281757, 173.31554013],
       [172.47119604, 173.26890398, 172.91296131],
       [173.70758215, 172.36311393, 171.43689046]])

In [90]:
a = np.random.normal(10,1,10)

print(a)
print(a.mean())
print(np.median(a))

[11.45981766 10.47126216  9.48686121  9.60310957 10.60019866  7.7079854
 10.55663529 10.56167358 10.0015739  10.85562009]
10.130473752217378
10.513948724704893


In [94]:
a = np.array([[1,2],[3,4]])

print(a)
print(a.mean())
print(a.mean(axis=0))
print(a.mean(axis=1))

[[1 2]
 [3 4]]
2.5
[2. 3.]
[1.5 3.5]


In [97]:
np.std(a)

1.118033988749895